# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ML CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test.py
    - name: Build Docker image
      run: |
          docker build -t ml-api_new .
          
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Push Docker image
      run: |
          docker tag ml-api_new:latest ${{secrets.DOCKER_HUB_USERNAME}}/ml-api_new:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ml-api_new:latest
